name: Deploy static content to Pages

on:
  push:
    branches: ['master'] # Change to your default branch if different

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Ensure this command outputs to the correct directory

      - name: List build directory
        run: ls -la build # Adjust based on your build output directory

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build' # Adjust based on your actual build output directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
